Ext.define('pxp.model.VoBoFondo', {
    extend: 'Ext.data.Model',
    config: {
    	idProperty :'id_cuenta_doc',
	    fields: [
			  {name:'id_cuenta_doc', type: 'numeric'},
			  {name:'id_presupuesto', type: 'numeric'},
			  {name:'desc_presupuesto', type: 'string'},
			  {name:'id_empleado', type: 'numeric'},
			  {name:'desc_empleado', type: 'string'},
			  {name:'id_categoria', type: 'numeric'},
			  {name:'desc_categoria', type: 'string'},
			  {name:'fecha_ini', type: 'date',dateFormat:'Y-m-d'},
			  {name:'fecha_fin', type: 'date',dateFormat:'Y-m-d'},  
			  {name:'tipo_pago', type: 'string'},
			  {name:'tipo_contrato', type: 'string'},
			  {name:'id_usuario_rendicion', type: 'numeric'},
			  {name:'desc_usuario', type: 'string'},
			  {name:'estado', type: 'string'},
			  {name:'nro_documento', type: 'string'},
			  {name:'fecha_reg', type: 'date',dateFormat:'Y-m-d'},
			  {name:'motivo', type: 'string'},
			  {name:'recorrido', type: 'string'},
			  {name:'observaciones', type: 'string'},
			  {name:'id_depto', type: 'numeric'},
			  {name:'desc_depto', type: 'string'},
			  {name:'id_moneda', type: 'numeric'},
			  {name:'desc_moneda', type: 'string'},
			  {name:'fecha_sol', type: 'date',dateFormat:'Y-m-d'},
			  {name:'fa_solicitud', type: 'string'},
			  {name:'id_caja', type: 'numeric'},
			  {name:'desc_caja', type: 'string'},
			  {name:'id_cajero', type: 'numeric'},
			  {name:'desc_cajero', type: 'string'},
			  {name:'importe', type: 'numeric'},
			  {name:'id_parametro', type: 'numeric'},
			  {name:'desc_parametro', type: 'string'},
			  {name:'resp_registro', type: 'string'},
			  {name:'tipo_pago_fin', type: 'string'},
			  {name:'id_cuenta_bancaria', type: 'numeric'},
			  {name:'id_cuenta_bancaria_fin', type: 'numeric'},
			  {name:'id_caja_fin', type: 'numeric'},
			  {name:'id_cajero_fin', type: 'numeric'},
			  {name:'nro_deposito', type: 'string'},
			  {name:'desc_cuenta_bancaria_fin', type: 'string'},
			  {name:'desc_caja_fin', type: 'string'},
			  {name:'desc_cajero_fin', type: 'string'},
			  {name:'id_autorizacion', type: 'numeric'},
			  {name:'desc_autorizacion', type: 'string'},
			  {name:'nombre_cheque', type: 'string'},
			  {name:'nro_cheque', type: 'string'},
			  {name:'tipo_cuenta_doc', type: 'string'},
			  {name:'fk_id_cuenta_doc', type: 'numeric'},
			  {name:'id_usuario_reg', type: 'numeric'},
			  {name:'id_comprobante', type: 'numeric'},
			  {name:'fecha_aut_rendicion', type: 'date',dateFormat:'Y-m-d'},
			  {name:'cant_rend_registradas', type: 'numeric'},
			  {name:'cant_rend_finalizadas', type: 'numeric'},
			  {name:'cant_rend_contabilizadas', type: 'numeric'},
			  {name:'codigo_caja', type: 'string'},
			  {name:'respuesta_aprobador', type: 'string'},
			  {name:'saldo_solicitante', type: 'numeric'},
			  {name:'importe_detalle', type: 'numeric'},
			  {name:'id_presupuesto_detalle', type: 'numeric'},
			  {name:'saldo_rendiciones', type: 'numeric'},
			  {name:'saldo_retenciones', type: 'numeric'},
			  {name:'saldo_depositar', type: 'numeric'}    
			 ]
     }  
});